CREATE TABLE IF NOT EXISTS App (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title VARCHAR(255) NOT NULL,
    developer VARCHAR(255) NOT NULL,
    exeDir VARCHAR(512) NOT NULL,
    imgDir VARCHAR(255) NOT NULL
);